export type SeedPricingPlan = {
  name: string;
  priceUsdCents: number | null;
  billingCycle: "monthly" | "yearly" | "one_time" | "usage" | null;
  features: string[];
};

export type SeedTool = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  websiteUrl: string;
  pricingModel: "FREE" | "FREEMIUM" | "PAID" | "USAGE_BASED" | "CONTACT_SALES";
  categorySlug: string;
  tags?: string[];
  pricingPlans?: SeedPricingPlan[];
};

export type SeedCategory = {
  slug: string;
  name: string;
  description: string;
};

export const categories: SeedCategory[] = [
  { slug: "chatbots", name: "Chatbots & Assistentes", description: "Assistentes conversacionais de uso geral baseados em LLMs." },
  { slug: "escrita", name: "Escrita & Conteúdo", description: "Geração e edição de texto, copywriting, redação assistida." },
  { slug: "imagem", name: "Geração de Imagem", description: "Criação e edição de imagens via IA generativa." },
  { slug: "video", name: "Vídeo", description: "Geração, edição e legendagem de vídeo com IA." },
  { slug: "audio", name: "Áudio & Voz", description: "Síntese de voz, clonagem de voz e edição de áudio." },
  { slug: "musica", name: "Geração de Música", description: "Composição e geração de música via IA." },
  { slug: "codigo", name: "Código & Desenvolvimento", description: "Assistentes de programação e agentes de engenharia." },
  { slug: "produtividade", name: "Produtividade & Agentes", description: "Automação de tarefas e agentes multipropósito." },
  { slug: "busca", name: "Busca & Pesquisa", description: "Motores de busca e pesquisa acadêmica com IA." },
  { slug: "dados", name: "Dados & Analytics", description: "Análise de dados e machine learning sem código." },
  { slug: "design", name: "Design & Branding", description: "Ferramentas de design visual e identidade de marca." },
  { slug: "marketing", name: "Marketing & Vendas", description: "Prospecção, copy de vendas e automação de marketing." },
  { slug: "atendimento", name: "Atendimento ao Cliente", description: "Chatbots de suporte e automação de atendimento." },
  { slug: "automacao", name: "Automação & Workflows", description: "RPA e automação de processos entre sistemas." },
  { slug: "seo", name: "SEO & Otimização de Conteúdo", description: "Otimização de conteúdo para mecanismos de busca." },
  { slug: "educacao", name: "Educação & Aprendizado", description: "Tutoria e aprendizado de idiomas assistido por IA." },
  { slug: "saude", name: "Saúde", description: "Assistência clínica e bem-estar com IA." },
  { slug: "juridico", name: "Jurídico", description: "Análise de contratos e pesquisa jurídica com IA." },
  { slug: "financas", name: "Finanças", description: "Contabilidade, gestão financeira pessoal e corporativa." },
  { slug: "reunioes", name: "Reuniões & Transcrição", description: "Transcrição, resumo e atas automáticas de reuniões." },
  { slug: "notas", name: "Notas & Conhecimento", description: "Gestão de notas e conhecimento pessoal com IA." },
  { slug: "apresentacoes", name: "Apresentações & Slides", description: "Geração automática de slides e apresentações." },
  { slug: "sites", name: "Criação de Sites", description: "Construção de sites e landing pages com IA." },
  { slug: "deteccao", name: "Detecção de Conteúdo de IA", description: "Detecção de plágio e texto gerado por IA." },
  { slug: "3d-jogos", name: "3D & Jogos", description: "Geração de modelos 3D e assets para jogos." },
];

export const tools: SeedTool[] = [
  // Chatbots & Assistentes
  { slug: "chatgpt", name: "ChatGPT", tagline: "Assistente conversacional da OpenAI", description: "Chatbot de uso geral para conversa, escrita, análise e código, baseado nos modelos GPT.", websiteUrl: "https://chat.openai.com", pricingModel: "FREEMIUM", categorySlug: "chatbots" },
  { slug: "claude-ai", name: "Claude", tagline: "Assistente de IA da Anthropic", description: "Assistente conversacional focado em raciocínio, escrita longa e uso seguro de ferramentas.", websiteUrl: "https://claude.ai", pricingModel: "FREEMIUM", categorySlug: "chatbots" },
  { slug: "google-gemini", name: "Google Gemini", tagline: "Assistente de IA multimodal do Google", description: "Chatbot multimodal integrado ao ecossistema Google Workspace e Android.", websiteUrl: "https://gemini.google.com", pricingModel: "FREEMIUM", categorySlug: "chatbots" },
  { slug: "microsoft-copilot", name: "Microsoft Copilot", tagline: "Assistente de IA integrado ao Windows e Office", description: "Assistente de IA da Microsoft integrado ao Windows, Edge e Office 365.", websiteUrl: "https://copilot.microsoft.com", pricingModel: "FREEMIUM", categorySlug: "chatbots" },
  { slug: "perplexity", name: "Perplexity", tagline: "Chatbot de respostas com fontes citadas", description: "Assistente de busca conversacional que responde com citações e fontes verificáveis.", websiteUrl: "https://www.perplexity.ai", pricingModel: "FREEMIUM", categorySlug: "chatbots" },
  { slug: "meta-ai", name: "Meta AI", tagline: "Assistente de IA da Meta", description: "Assistente conversacional integrado ao WhatsApp, Instagram e Facebook.", websiteUrl: "https://www.meta.ai", pricingModel: "FREE", categorySlug: "chatbots" },
  { slug: "pi-ai", name: "Pi", tagline: "Assistente pessoal conversacional", description: "Chatbot da Inflection AI focado em conversas pessoais empáticas.", websiteUrl: "https://pi.ai", pricingModel: "FREE", categorySlug: "chatbots" },
  { slug: "character-ai", name: "Character.AI", tagline: "Crie e converse com personagens de IA", description: "Plataforma para criar e conversar com personagens de IA personalizados.", websiteUrl: "https://character.ai", pricingModel: "FREEMIUM", categorySlug: "chatbots" },
  { slug: "poe", name: "Poe", tagline: "Acesso a múltiplos modelos de IA em um só lugar", description: "Plataforma da Quora que reúne diversos chatbots e modelos de IA em uma interface.", websiteUrl: "https://poe.com", pricingModel: "FREEMIUM", categorySlug: "chatbots" },
  { slug: "grok", name: "Grok", tagline: "Assistente de IA da xAI", description: "Chatbot da xAI integrado à plataforma X, com acesso a informações em tempo real.", websiteUrl: "https://x.ai", pricingModel: "PAID", categorySlug: "chatbots" },
  { slug: "deepseek-chat", name: "DeepSeek Chat", tagline: "Assistente de IA de código aberto", description: "Chatbot baseado em modelos open-weight de alto desempenho da DeepSeek.", websiteUrl: "https://chat.deepseek.com", pricingModel: "FREEMIUM", categorySlug: "chatbots" },
  { slug: "mistral-le-chat", name: "Le Chat", tagline: "Assistente de IA da Mistral", description: "Chatbot da Mistral AI com foco em desempenho e suporte a múltiplos idiomas.", websiteUrl: "https://chat.mistral.ai", pricingModel: "FREEMIUM", categorySlug: "chatbots" },
  { slug: "huggingchat", name: "HuggingChat", tagline: "Chatbot open-source da Hugging Face", description: "Interface de chat gratuita para experimentar modelos open-source da comunidade Hugging Face.", websiteUrl: "https://huggingface.co/chat", pricingModel: "FREE", categorySlug: "chatbots" },
  { slug: "replika", name: "Replika", tagline: "Companheiro de IA personalizável", description: "Aplicativo de companhia de IA com personalidade customizável e memória de longo prazo.", websiteUrl: "https://replika.com", pricingModel: "FREEMIUM", categorySlug: "chatbots" },
  { slug: "jan-ai", name: "Jan", tagline: "Assistente de IA local e open-source", description: "Aplicativo desktop para rodar modelos de linguagem localmente, sem depender da nuvem.", websiteUrl: "https://jan.ai", pricingModel: "FREE", categorySlug: "chatbots" },
  { slug: "lm-studio", name: "LM Studio", tagline: "Rode modelos de IA localmente no seu computador", description: "Aplicativo para baixar e rodar LLMs open-source localmente com interface gráfica.", websiteUrl: "https://lmstudio.ai", pricingModel: "FREE", categorySlug: "chatbots" },

  // Escrita & Conteúdo
  { slug: "jasper", name: "Jasper", tagline: "Plataforma de IA para conteúdo de marketing", description: "Geração de conteúdo de marketing em escala com controle de marca e tom de voz.", websiteUrl: "https://www.jasper.ai", pricingModel: "PAID", categorySlug: "escrita" },
  { slug: "copy-ai", name: "Copy.ai", tagline: "Geração de copy de marketing e vendas", description: "Plataforma de IA para gerar textos de marketing, e-mails e copy de vendas.", websiteUrl: "https://www.copy.ai", pricingModel: "FREEMIUM", categorySlug: "escrita" },
  { slug: "writesonic", name: "Writesonic", tagline: "Escrita de conteúdo e artigos com IA", description: "Geração de artigos, anúncios e conteúdo de blog otimizado para SEO.", websiteUrl: "https://writesonic.com", pricingModel: "FREEMIUM", categorySlug: "escrita" },
  { slug: "rytr", name: "Rytr", tagline: "Assistente de escrita de IA acessível", description: "Ferramenta de redação assistida por IA com mais de 40 casos de uso e tons.", websiteUrl: "https://rytr.me", pricingModel: "FREEMIUM", categorySlug: "escrita" },
  { slug: "sudowrite", name: "Sudowrite", tagline: "IA para escritores de ficção", description: "Assistente de escrita criativa voltado para autores de ficção e roteiristas.", websiteUrl: "https://www.sudowrite.com", pricingModel: "PAID", categorySlug: "escrita" },
  { slug: "grammarly", name: "Grammarly", tagline: "Revisão de gramática e estilo com IA", description: "Corretor de gramática, estilo e tom que funciona em qualquer site ou app.", websiteUrl: "https://www.grammarly.com", pricingModel: "FREEMIUM", categorySlug: "escrita" },
  { slug: "quillbot", name: "QuillBot", tagline: "Paráfrase e revisão de texto com IA", description: "Ferramenta de paráfrase, resumo e verificação gramatical para textos acadêmicos.", websiteUrl: "https://quillbot.com", pricingModel: "FREEMIUM", categorySlug: "escrita" },
  { slug: "wordtune", name: "Wordtune", tagline: "Reescreva frases com IA", description: "Sugestões de reescrita em tempo real para deixar o texto mais claro e natural.", websiteUrl: "https://www.wordtune.com", pricingModel: "FREEMIUM", categorySlug: "escrita" },
  { slug: "prowritingaid", name: "ProWritingAid", tagline: "Editor de gramática e estilo para escritores", description: "Análise profunda de estilo, gramática e legibilidade para textos longos.", websiteUrl: "https://prowritingaid.com", pricingModel: "FREEMIUM", categorySlug: "escrita" },
  { slug: "anyword", name: "Anyword", tagline: "Copy de marketing com previsão de performance", description: "Geração de copy com pontuação preditiva de performance por público-alvo.", websiteUrl: "https://anyword.com", pricingModel: "PAID", categorySlug: "escrita" },
  { slug: "notion-ai", name: "Notion AI", tagline: "IA integrada ao Notion", description: "Assistente de escrita e resumo integrado diretamente às páginas do Notion.", websiteUrl: "https://www.notion.so/product/ai", pricingModel: "PAID", categorySlug: "escrita" },
  { slug: "lex", name: "Lex", tagline: "Editor de texto com IA integrada", description: "Editor de documentos com IA integrada para sugestões e continuação de texto.", websiteUrl: "https://lex.page", pricingModel: "FREEMIUM", categorySlug: "escrita" },
  { slug: "copysmith", name: "Copysmith", tagline: "Geração de conteúdo de e-commerce com IA", description: "Geração de descrições de produto e copy de e-commerce em escala.", websiteUrl: "https://copysmith.ai", pricingModel: "PAID", categorySlug: "escrita" },
  { slug: "hypotenuse-ai", name: "Hypotenuse AI", tagline: "Conteúdo de e-commerce e blog com IA", description: "Geração automática de descrições de produto e artigos de blog a partir de dados.", websiteUrl: "https://www.hypotenuse.ai", pricingModel: "PAID", categorySlug: "escrita" },
  { slug: "simplified", name: "Simplified", tagline: "Suite de marketing e design com IA", description: "Plataforma all-in-one de criação de conteúdo, design e copy para equipes de marketing.", websiteUrl: "https://simplified.com", pricingModel: "FREEMIUM", categorySlug: "escrita" },

  // Geração de Imagem
  { slug: "midjourney", name: "Midjourney", tagline: "Geração de imagens artísticas com IA", description: "Um dos geradores de imagem mais populares, conhecido pela qualidade artística.", websiteUrl: "https://www.midjourney.com", pricingModel: "PAID", categorySlug: "imagem" },
  { slug: "dall-e", name: "DALL·E", tagline: "Geração de imagens da OpenAI", description: "Modelo de geração de imagens da OpenAI, integrado ao ChatGPT.", websiteUrl: "https://openai.com/dall-e-3", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "stable-diffusion", name: "Stable Diffusion", tagline: "Modelo de imagem open-source da Stability AI", description: "Modelo de difusão open-source para geração de imagens, usado por diversas ferramentas.", websiteUrl: "https://stability.ai", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "adobe-firefly", name: "Adobe Firefly", tagline: "IA generativa da Adobe", description: "Geração de imagens e efeitos integrados ao Photoshop e Creative Cloud.", websiteUrl: "https://firefly.adobe.com", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "leonardo-ai", name: "Leonardo.Ai", tagline: "Geração de imagens para criadores", description: "Plataforma de geração de imagens com modelos treináveis e controle fino de estilo.", websiteUrl: "https://leonardo.ai", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "ideogram", name: "Ideogram", tagline: "Geração de imagens com texto legível", description: "Gerador de imagens conhecido por renderizar texto de forma legível dentro das imagens.", websiteUrl: "https://ideogram.ai", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "playground-ai", name: "Playground AI", tagline: "Editor de imagens com IA generativa", description: "Plataforma de criação e edição de imagens combinando vários modelos de IA.", websiteUrl: "https://playground.com", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "nightcafe", name: "NightCafe", tagline: "Comunidade de arte gerada por IA", description: "Gerador de arte com IA com forte componente de comunidade e desafios.", websiteUrl: "https://nightcafe.studio", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "recraft", name: "Recraft", tagline: "Geração de imagens e vetores para design", description: "Geração de imagens, ícones e vetores com foco em fluxos de trabalho de design.", websiteUrl: "https://www.recraft.ai", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "krea-ai", name: "Krea AI", tagline: "Geração de imagem em tempo real", description: "Geração e upscaling de imagens em tempo real com controle interativo.", websiteUrl: "https://www.krea.ai", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "civitai", name: "Civitai", tagline: "Comunidade de modelos de geração de imagem", description: "Repositório comunitário de modelos e checkpoints para geração de imagem.", websiteUrl: "https://civitai.com", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "dreamstudio", name: "DreamStudio", tagline: "Interface oficial do Stable Diffusion", description: "Interface web oficial da Stability AI para geração de imagens via Stable Diffusion.", websiteUrl: "https://dreamstudio.ai", pricingModel: "USAGE_BASED", categorySlug: "imagem" },
  { slug: "lexica", name: "Lexica", tagline: "Buscador e gerador de imagens de IA", description: "Mecanismo de busca de prompts e imagens geradas por IA, com gerador integrado.", websiteUrl: "https://lexica.art", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "openart", name: "OpenArt", tagline: "Criação de arte e fluxos de IA visual", description: "Plataforma de geração de imagens com biblioteca de prompts e workflows visuais.", websiteUrl: "https://openart.ai", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "scenario", name: "Scenario", tagline: "Geração de assets de jogos com IA", description: "Geração de assets visuais customizados para estúdios de jogos.", websiteUrl: "https://www.scenario.com", pricingModel: "PAID", categorySlug: "imagem" },
  { slug: "magnific-ai", name: "Magnific AI", tagline: "Upscaling de imagem com IA", description: "Upscaler de imagens com adição de detalhes realistas via IA generativa.", websiteUrl: "https://magnific.ai", pricingModel: "PAID", categorySlug: "imagem" },
  { slug: "photoroom", name: "Photoroom", tagline: "Edição de fotos de produto com IA", description: "Remoção de fundo e edição de fotos de produto para e-commerce.", websiteUrl: "https://www.photoroom.com", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "remove-bg", name: "Remove.bg", tagline: "Remoção automática de fundo de imagens", description: "Remove o fundo de imagens automaticamente em segundos.", websiteUrl: "https://www.remove.bg", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "clipdrop", name: "Clipdrop", tagline: "Kit de ferramentas visuais com IA", description: "Conjunto de ferramentas de edição visual com IA da Stability AI.", websiteUrl: "https://clipdrop.co", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "remini", name: "Remini", tagline: "Melhoria de qualidade de fotos com IA", description: "Aumenta a resolução e qualidade de fotos antigas ou de baixa qualidade.", websiteUrl: "https://www.remini.ai", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "freepik-ai", name: "Freepik AI", tagline: "Geração de imagens dentro do Freepik", description: "Suite de geração de imagens integrada ao banco de imagens Freepik.", websiteUrl: "https://www.freepik.com/ai", pricingModel: "FREEMIUM", categorySlug: "imagem" },
  { slug: "microsoft-designer", name: "Microsoft Designer", tagline: "Geração de imagens e designs da Microsoft", description: "Ferramenta de design gráfico e geração de imagens com IA da Microsoft.", websiteUrl: "https://designer.microsoft.com", pricingModel: "FREEMIUM", categorySlug: "imagem" },

  // Vídeo
  { slug: "runway", name: "Runway", tagline: "Geração e edição de vídeo com IA", description: "Suite de ferramentas de IA generativa para vídeo usada por criadores e estúdios.", websiteUrl: "https://runwayml.com", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "pika", name: "Pika", tagline: "Geração de vídeo a partir de texto e imagem", description: "Gerador de vídeos curtos a partir de prompts de texto ou imagens.", websiteUrl: "https://pika.art", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "luma-dream-machine", name: "Luma Dream Machine", tagline: "Geração de vídeo realista com IA", description: "Modelo de geração de vídeo da Luma Labs com foco em realismo e física consistente.", websiteUrl: "https://lumalabs.ai/dream-machine", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "synthesia", name: "Synthesia", tagline: "Vídeos com avatares de IA", description: "Criação de vídeos corporativos com avatares falantes de IA em múltiplos idiomas.", websiteUrl: "https://www.synthesia.io", pricingModel: "PAID", categorySlug: "video" },
  { slug: "heygen", name: "HeyGen", tagline: "Avatares de vídeo com IA", description: "Geração de vídeos com avatares digitais e clonagem de voz para marketing.", websiteUrl: "https://www.heygen.com", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "d-id", name: "D-ID", tagline: "Vídeos falantes com IA", description: "Plataforma para criar vídeos com avatares falantes a partir de fotos e texto.", websiteUrl: "https://www.d-id.com", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "colossyan", name: "Colossyan", tagline: "Vídeos de treinamento com avatares de IA", description: "Criação de vídeos de treinamento corporativo com avatares de IA.", websiteUrl: "https://www.colossyan.com", pricingModel: "PAID", categorySlug: "video" },
  { slug: "pictory", name: "Pictory", tagline: "Transforme texto e artigos em vídeo", description: "Converte roteiros, artigos e blogs em vídeos automaticamente.", websiteUrl: "https://pictory.ai", pricingModel: "PAID", categorySlug: "video" },
  { slug: "invideo", name: "InVideo", tagline: "Editor de vídeo com IA para criadores", description: "Editor de vídeo online com templates e geração assistida por IA.", websiteUrl: "https://invideo.io", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "capcut", name: "CapCut", tagline: "Editor de vídeo para redes sociais", description: "Editor de vídeo gratuito popular para conteúdo de redes sociais, com recursos de IA.", websiteUrl: "https://www.capcut.com", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "veed-io", name: "Veed.io", tagline: "Edição de vídeo online com IA", description: "Editor de vídeo online com legendas automáticas e ferramentas de IA.", websiteUrl: "https://www.veed.io", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "kapwing", name: "Kapwing", tagline: "Editor de vídeo colaborativo com IA", description: "Editor de vídeo online colaborativo com recursos de legendagem automática.", websiteUrl: "https://www.kapwing.com", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "opus-clip", name: "Opus Clip", tagline: "Cortes virais a partir de vídeos longos", description: "Transforma vídeos longos em cortes curtos otimizados para redes sociais.", websiteUrl: "https://www.opus.pro", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "submagic", name: "Submagic", tagline: "Legendas automáticas para vídeos curtos", description: "Adiciona legendas estilizadas e efeitos automaticamente a vídeos curtos.", websiteUrl: "https://www.submagic.co", pricingModel: "PAID", categorySlug: "video" },
  { slug: "descript", name: "Descript", tagline: "Edição de vídeo e áudio como texto", description: "Edite vídeo e áudio editando uma transcrição de texto, com clonagem de voz.", websiteUrl: "https://www.descript.com", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "sora", name: "Sora", tagline: "Geração de vídeo da OpenAI", description: "Modelo de geração de vídeo a partir de texto desenvolvido pela OpenAI.", websiteUrl: "https://openai.com/sora", pricingModel: "PAID", categorySlug: "video" },
  { slug: "kling-ai", name: "Kling AI", tagline: "Geração de vídeo realista", description: "Modelo de geração de vídeo a partir de texto e imagem com alto realismo.", websiteUrl: "https://klingai.com", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "hour-one", name: "Hour One", tagline: "Vídeos automáticos com apresentadores de IA", description: "Geração de vídeos com apresentadores virtuais a partir de texto.", websiteUrl: "https://hourone.ai", pricingModel: "PAID", categorySlug: "video" },
  { slug: "elai-io", name: "Elai.io", tagline: "Criação de vídeos com avatares de IA", description: "Plataforma para criar vídeos automaticamente com avatares de IA a partir de texto.", websiteUrl: "https://elai.io", pricingModel: "PAID", categorySlug: "video" },
  { slug: "tavus", name: "Tavus", tagline: "Vídeos personalizados em escala com IA", description: "Geração de vídeos personalizados em massa usando avatares de IA.", websiteUrl: "https://www.tavus.io", pricingModel: "CONTACT_SALES", categorySlug: "video" },
  { slug: "google-veo", name: "Veo", tagline: "Geração de vídeo do Google DeepMind", description: "Modelo de geração de vídeo de alta qualidade desenvolvido pelo Google DeepMind.", websiteUrl: "https://deepmind.google/technologies/veo", pricingModel: "CONTACT_SALES", categorySlug: "video" },
  { slug: "virbo", name: "Wondershare Virbo", tagline: "Vídeos com avatar de IA da Wondershare", description: "Geração de vídeos de marketing com avatares de IA falantes.", websiteUrl: "https://virbo.wondershare.com", pricingModel: "FREEMIUM", categorySlug: "video" },
  { slug: "steve-ai", name: "Steve.ai", tagline: "Transforme texto em vídeo animado", description: "Geração de vídeos animados ou live-action a partir de roteiros de texto.", websiteUrl: "https://www.steve.ai", pricingModel: "FREEMIUM", categorySlug: "video" },

  // Áudio & Voz
  { slug: "elevenlabs", name: "ElevenLabs", tagline: "Síntese e clonagem de voz realista", description: "Geração de voz e clonagem de voz de alta qualidade para diversos idiomas.", websiteUrl: "https://elevenlabs.io", pricingModel: "FREEMIUM", categorySlug: "audio" },
  { slug: "murf-ai", name: "Murf AI", tagline: "Locução com voz de IA para vídeos", description: "Geração de locução profissional com voz de IA para vídeos e apresentações.", websiteUrl: "https://murf.ai", pricingModel: "FREEMIUM", categorySlug: "audio" },
  { slug: "play-ht", name: "Play.ht", tagline: "Texto para fala com vozes realistas", description: "Conversão de texto em fala com vozes ultra-realistas e clonagem de voz.", websiteUrl: "https://play.ht", pricingModel: "FREEMIUM", categorySlug: "audio" },
  { slug: "wellsaid-labs", name: "WellSaid Labs", tagline: "Vozes de IA para narração corporativa", description: "Vozes sintéticas de alta qualidade voltadas para narração corporativa e e-learning.", websiteUrl: "https://wellsaidlabs.com", pricingModel: "PAID", categorySlug: "audio" },
  { slug: "resemble-ai", name: "Resemble AI", tagline: "Clonagem e geração de voz com IA", description: "Plataforma de clonagem de voz e geração de fala em tempo real.", websiteUrl: "https://www.resemble.ai", pricingModel: "USAGE_BASED", categorySlug: "audio" },
  { slug: "speechify", name: "Speechify", tagline: "Transforme texto em áudio para ouvir", description: "Converte textos, PDFs e artigos em áudio para escuta em qualquer lugar.", websiteUrl: "https://speechify.com", pricingModel: "FREEMIUM", categorySlug: "audio" },
  { slug: "adobe-podcast", name: "Adobe Podcast", tagline: "Melhoria de qualidade de áudio com IA", description: "Remove ruído e melhora a qualidade de gravações de voz automaticamente.", websiteUrl: "https://podcast.adobe.com", pricingModel: "FREEMIUM", categorySlug: "audio" },
  { slug: "krisp", name: "Krisp", tagline: "Cancelamento de ruído em chamadas com IA", description: "Remove ruído de fundo e eco em tempo real durante chamadas e gravações.", websiteUrl: "https://krisp.ai", pricingModel: "FREEMIUM", categorySlug: "audio" },
  { slug: "cleanvoice", name: "Cleanvoice", tagline: "Limpeza automática de podcasts", description: "Remove automaticamente gagueiras, pausas e ruídos de gravações de podcast.", websiteUrl: "https://cleanvoice.ai", pricingModel: "USAGE_BASED", categorySlug: "audio" },
  { slug: "lovo-ai", name: "LOVO AI", tagline: "Vozes sintéticas para conteúdo de mídia", description: "Geração de voz sintética e dublagem de IA para vídeos e podcasts.", websiteUrl: "https://lovo.ai", pricingModel: "FREEMIUM", categorySlug: "audio" },
  { slug: "voicemod", name: "Voicemod", tagline: "Modificador de voz em tempo real", description: "Altera a voz em tempo real para jogos, chamadas e streaming.", websiteUrl: "https://www.voicemod.net", pricingModel: "FREEMIUM", categorySlug: "audio" },

  // Geração de Música
  { slug: "suno", name: "Suno", tagline: "Geração de música completa com IA", description: "Cria músicas completas com letra e melodia a partir de um prompt de texto.", websiteUrl: "https://suno.com", pricingModel: "FREEMIUM", categorySlug: "musica" },
  { slug: "udio", name: "Udio", tagline: "Criação de músicas realistas com IA", description: "Geração de faixas musicais realistas a partir de descrições de texto.", websiteUrl: "https://www.udio.com", pricingModel: "FREEMIUM", categorySlug: "musica" },
  { slug: "aiva", name: "AIVA", tagline: "Composição musical com IA", description: "Compositor de IA usado para trilhas sonoras de filmes, jogos e publicidade.", websiteUrl: "https://www.aiva.ai", pricingModel: "FREEMIUM", categorySlug: "musica" },
  { slug: "soundraw", name: "Soundraw", tagline: "Música royalty-free gerada por IA", description: "Geração de trilhas musicais royalty-free customizáveis por humor e gênero.", websiteUrl: "https://soundraw.io", pricingModel: "PAID", categorySlug: "musica" },
  { slug: "boomy", name: "Boomy", tagline: "Crie e publique músicas com IA", description: "Permite criar e distribuir músicas geradas por IA em plataformas de streaming.", websiteUrl: "https://boomy.com", pricingModel: "FREEMIUM", categorySlug: "musica" },
  { slug: "mubert", name: "Mubert", tagline: "Música gerada por IA em tempo real", description: "Geração de música royalty-free em tempo real via API para criadores.", websiteUrl: "https://mubert.com", pricingModel: "FREEMIUM", categorySlug: "musica" },
  { slug: "lalal-ai", name: "LALAL.AI", tagline: "Separação de vocais e instrumentos com IA", description: "Separa vocais, instrumentos e ruído de faixas de áudio automaticamente.", websiteUrl: "https://www.lalal.ai", pricingModel: "USAGE_BASED", categorySlug: "musica" },
  { slug: "loudly", name: "Loudly", tagline: "Geração de música para criadores de conteúdo", description: "Plataforma de geração musical com foco em criadores de conteúdo social.", websiteUrl: "https://www.loudly.com", pricingModel: "FREEMIUM", categorySlug: "musica" },
  { slug: "beatoven-ai", name: "Beatoven.ai", tagline: "Trilhas sonoras personalizadas com IA", description: "Compõe trilhas sonoras originais e livres de direitos para vídeos.", websiteUrl: "https://www.beatoven.ai", pricingModel: "FREEMIUM", categorySlug: "musica" },

  // Código & Desenvolvimento
  { slug: "github-copilot", name: "GitHub Copilot", tagline: "Par de programação com IA da GitHub", description: "Autocomplete e geração de código com IA integrado a editores populares.", websiteUrl: "https://github.com/features/copilot", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "cursor", name: "Cursor", tagline: "Editor de código com IA nativa", description: "Editor de código construído do zero com IA integrada para edição e chat.", websiteUrl: "https://www.cursor.com", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "replit-ai", name: "Replit AI", tagline: "Agente de programação no navegador", description: "Assistente de código integrado ao IDE online Replit, com geração de apps completos.", websiteUrl: "https://replit.com/ai", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "tabnine", name: "Tabnine", tagline: "Autocomplete de código com IA privada", description: "Assistente de código com foco em privacidade e modelos treináveis na sua base.", websiteUrl: "https://www.tabnine.com", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "codeium-windsurf", name: "Windsurf", tagline: "Editor de código agentic com IA", description: "Editor de código com agentes de IA capazes de executar tarefas multi-arquivo.", websiteUrl: "https://windsurf.com", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "sourcegraph-cody", name: "Cody", tagline: "Assistente de código com contexto de repositório", description: "Assistente de IA da Sourcegraph com entendimento profundo do código-base.", websiteUrl: "https://sourcegraph.com/cody", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "amazon-q-developer", name: "Amazon Q Developer", tagline: "Assistente de código da AWS", description: "Assistente de IA da AWS para desenvolvimento, revisão e migração de código.", websiteUrl: "https://aws.amazon.com/q/developer", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "phind", name: "Phind", tagline: "Mecanismo de busca para desenvolvedores", description: "Motor de busca e chat especializado em responder perguntas técnicas de código.", websiteUrl: "https://www.phind.com", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "v0", name: "v0", tagline: "Geração de interfaces com IA da Vercel", description: "Gera componentes e interfaces de UI em React a partir de prompts de texto.", websiteUrl: "https://v0.dev", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "bolt-new", name: "Bolt.new", tagline: "Crie apps full-stack com IA no navegador", description: "Gera e executa aplicações full-stack completas direto no navegador via IA.", websiteUrl: "https://bolt.new", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "lovable", name: "Lovable", tagline: "Construa apps full-stack com IA", description: "Plataforma de geração de apps full-stack a partir de descrições em linguagem natural.", websiteUrl: "https://lovable.dev", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "devin", name: "Devin", tagline: "Agente de engenharia de software autônomo", description: "Agente de IA da Cognition capaz de planejar e executar tarefas de engenharia de ponta a ponta.", websiteUrl: "https://cognition.ai", pricingModel: "CONTACT_SALES", categorySlug: "codigo" },
  { slug: "zed", name: "Zed", tagline: "Editor de código colaborativo e rápido com IA", description: "Editor de código de alta performance com colaboração em tempo real e IA integrada.", websiteUrl: "https://zed.dev", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "jetbrains-ai", name: "JetBrains AI Assistant", tagline: "IA integrada às IDEs JetBrains", description: "Assistente de IA integrado a IntelliJ, PyCharm, WebStorm e outras IDEs JetBrains.", websiteUrl: "https://www.jetbrains.com/ai", pricingModel: "PAID", categorySlug: "codigo" },
  { slug: "coderabbit", name: "CodeRabbit", tagline: "Revisão de pull requests com IA", description: "Revisa automaticamente pull requests, sugerindo correções e apontando riscos.", websiteUrl: "https://www.coderabbit.ai", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "greptile", name: "Greptile", tagline: "IA que entende todo o seu codebase", description: "Indexa e entende repositórios inteiros para revisão de código e respostas técnicas.", websiteUrl: "https://www.greptile.com", pricingModel: "PAID", categorySlug: "codigo" },
  { slug: "mintlify", name: "Mintlify", tagline: "Documentação técnica gerada por IA", description: "Geração e manutenção automática de documentação técnica de APIs e produtos.", websiteUrl: "https://mintlify.com", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "snyk-code", name: "Snyk Code", tagline: "Segurança de código com IA", description: "Detecção de vulnerabilidades de segurança em código-fonte em tempo real.", websiteUrl: "https://snyk.io/product/snyk-code", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "qodo", name: "Qodo", tagline: "Geração de testes automatizados com IA", description: "Geração automática de testes de software e revisão de qualidade de código.", websiteUrl: "https://www.qodo.ai", pricingModel: "FREEMIUM", categorySlug: "codigo" },
  { slug: "continue-dev", name: "Continue", tagline: "Assistente de código open-source", description: "Extensão open-source para IDEs que conecta a diversos modelos de IA para codificação.", websiteUrl: "https://continue.dev", pricingModel: "FREE", categorySlug: "codigo" },
  { slug: "aider", name: "Aider", tagline: "Par de programação via terminal com IA", description: "Ferramenta de linha de comando que edita código no seu repositório local via IA.", websiteUrl: "https://aider.chat", pricingModel: "FREE", categorySlug: "codigo" },
  { slug: "warp", name: "Warp", tagline: "Terminal moderno com IA integrada", description: "Terminal reinventado com autocomplete, blocos de comando e IA integrada.", websiteUrl: "https://www.warp.dev", pricingModel: "FREEMIUM", categorySlug: "codigo" },

  // Produtividade & Agentes
  { slug: "zapier", name: "Zapier", tagline: "Automação entre apps com IA", description: "Conecta milhares de aplicativos para automatizar fluxos de trabalho, com recursos de IA.", websiteUrl: "https://zapier.com", pricingModel: "FREEMIUM", categorySlug: "produtividade" },
  { slug: "make", name: "Make", tagline: "Automação visual de workflows", description: "Plataforma visual de automação de processos entre aplicativos e APIs.", websiteUrl: "https://www.make.com", pricingModel: "FREEMIUM", categorySlug: "produtividade" },
  { slug: "n8n", name: "n8n", tagline: "Automação de workflows open-source", description: "Ferramenta open-source de automação de workflows com nós de IA integrados.", websiteUrl: "https://n8n.io", pricingModel: "FREEMIUM", categorySlug: "produtividade" },
  { slug: "autogpt", name: "AutoGPT", tagline: "Agente autônomo de IA open-source", description: "Framework open-source para criar agentes de IA autônomos que executam tarefas complexas.", websiteUrl: "https://agpt.co", pricingModel: "FREE", categorySlug: "produtividade" },
  { slug: "agentgpt", name: "AgentGPT", tagline: "Crie agentes de IA autônomos no navegador", description: "Permite configurar e implantar agentes de IA autônomos direto do navegador.", websiteUrl: "https://agentgpt.reworkd.ai", pricingModel: "FREEMIUM", categorySlug: "produtividade" },
  { slug: "crewai", name: "CrewAI", tagline: "Orquestração de agentes de IA colaborativos", description: "Framework para orquestrar múltiplos agentes de IA trabalhando em conjunto.", websiteUrl: "https://www.crewai.com", pricingModel: "FREEMIUM", categorySlug: "produtividade" },
  { slug: "mem", name: "Mem", tagline: "Segunda memória com IA", description: "Aplicativo de notas com IA que organiza e recupera informações automaticamente.", websiteUrl: "https://mem.ai", pricingModel: "PAID", categorySlug: "produtividade" },
  { slug: "motion", name: "Motion", tagline: "Planejamento de agenda automatizado com IA", description: "Organiza automaticamente sua agenda e tarefas com base em prioridades.", websiteUrl: "https://www.usemotion.com", pricingModel: "PAID", categorySlug: "produtividade" },
  { slug: "reclaim-ai", name: "Reclaim AI", tagline: "Agendamento inteligente de tarefas", description: "Bloqueia automaticamente tempo na agenda para tarefas e hábitos importantes.", websiteUrl: "https://reclaim.ai", pricingModel: "FREEMIUM", categorySlug: "produtividade" },
  { slug: "superhuman", name: "Superhuman", tagline: "Cliente de e-mail rápido com IA", description: "Cliente de e-mail premium com recursos de IA para triagem e redação rápida.", websiteUrl: "https://superhuman.com", pricingModel: "PAID", categorySlug: "produtividade" },
  { slug: "taskade", name: "Taskade", tagline: "Gestão de tarefas com agentes de IA", description: "Plataforma de produtividade com agentes de IA para gestão de tarefas e projetos.", websiteUrl: "https://www.taskade.com", pricingModel: "FREEMIUM", categorySlug: "produtividade" },
  { slug: "lindy", name: "Lindy", tagline: "Crie assistentes de IA sem código", description: "Plataforma no-code para criar assistentes e agentes de IA personalizados.", websiteUrl: "https://www.lindy.ai", pricingModel: "FREEMIUM", categorySlug: "produtividade" },
  { slug: "fyxer-ai", name: "Fyxer AI", tagline: "Assistente de e-mail com IA", description: "Organiza, prioriza e rascunha respostas de e-mail automaticamente.", websiteUrl: "https://fyxer.com", pricingModel: "PAID", categorySlug: "produtividade" },

  // Busca & Pesquisa
  { slug: "komo", name: "Komo", tagline: "Motor de busca com IA generativa", description: "Mecanismo de busca que combina resultados tradicionais com respostas geradas por IA.", websiteUrl: "https://komo.ai", pricingModel: "FREE", categorySlug: "busca" },
  { slug: "andi-search", name: "Andi", tagline: "Busca conversacional com IA", description: "Motor de busca que responde perguntas de forma conversacional, como um amigo.", websiteUrl: "https://andisearch.com", pricingModel: "FREE", categorySlug: "busca" },
  { slug: "kagi", name: "Kagi", tagline: "Busca premium sem anúncios", description: "Motor de busca pago, sem anúncios, com recursos de IA e foco em privacidade.", websiteUrl: "https://kagi.com", pricingModel: "PAID", categorySlug: "busca" },
  { slug: "elicit", name: "Elicit", tagline: "Pesquisa de literatura científica com IA", description: "Ferramenta de IA para encontrar e resumir artigos científicos relevantes.", websiteUrl: "https://elicit.com", pricingModel: "FREEMIUM", categorySlug: "busca" },
  { slug: "consensus", name: "Consensus", tagline: "Busca em papers científicos com IA", description: "Motor de busca que extrai respostas diretamente de artigos científicos.", websiteUrl: "https://consensus.app", pricingModel: "FREEMIUM", categorySlug: "busca" },
  { slug: "scite", name: "scite", tagline: "Análise de citações científicas com IA", description: "Analisa como artigos científicos são citados para avaliar confiabilidade.", websiteUrl: "https://scite.ai", pricingModel: "PAID", categorySlug: "busca" },
  { slug: "scispace", name: "SciSpace", tagline: "Leitura e pesquisa de papers com IA", description: "Plataforma para ler, entender e pesquisar artigos científicos com IA.", websiteUrl: "https://www.scispace.com", pricingModel: "FREEMIUM", categorySlug: "busca" },
  { slug: "semantic-scholar", name: "Semantic Scholar", tagline: "Busca acadêmica gratuita com IA", description: "Mecanismo de busca acadêmica gratuito mantido pelo Allen Institute for AI.", websiteUrl: "https://www.semanticscholar.org", pricingModel: "FREE", categorySlug: "busca" },

  // Dados & Analytics
  { slug: "datarobot", name: "DataRobot", tagline: "Plataforma enterprise de machine learning", description: "Plataforma de IA empresarial para construção e governança de modelos de ML.", websiteUrl: "https://www.datarobot.com", pricingModel: "CONTACT_SALES", categorySlug: "dados" },
  { slug: "h2o-ai", name: "H2O.ai", tagline: "Plataforma open-source de machine learning", description: "Plataforma de machine learning automatizado open-source e enterprise.", websiteUrl: "https://h2o.ai", pricingModel: "FREEMIUM", categorySlug: "dados" },
  { slug: "akkio", name: "Akkio", tagline: "Machine learning sem código", description: "Plataforma no-code para construir e implantar modelos preditivos.", websiteUrl: "https://www.akkio.com", pricingModel: "PAID", categorySlug: "dados" },
  { slug: "monkeylearn", name: "MonkeyLearn", tagline: "Análise de texto com machine learning", description: "Ferramentas de processamento de linguagem natural para análise de texto sem código.", websiteUrl: "https://monkeylearn.com", pricingModel: "PAID", categorySlug: "dados" },
  { slug: "obviously-ai", name: "Obviously AI", tagline: "Previsões de machine learning sem código", description: "Constrói modelos preditivos de machine learning sem escrever código.", websiteUrl: "https://www.obviously.ai", pricingModel: "PAID", categorySlug: "dados" },
  { slug: "julius-ai", name: "Julius AI", tagline: "Análise de dados conversacional com IA", description: "Analisa planilhas e dados através de uma conversa em linguagem natural.", websiteUrl: "https://julius.ai", pricingModel: "FREEMIUM", categorySlug: "dados" },
  { slug: "hex", name: "Hex", tagline: "Notebooks colaborativos de dados com IA", description: "Plataforma de notebooks colaborativos para análise de dados com assistência de IA.", websiteUrl: "https://hex.tech", pricingModel: "FREEMIUM", categorySlug: "dados" },
  { slug: "thoughtspot", name: "ThoughtSpot", tagline: "Analytics com busca em linguagem natural", description: "Plataforma de business intelligence que responde perguntas em linguagem natural.", websiteUrl: "https://www.thoughtspot.com", pricingModel: "CONTACT_SALES", categorySlug: "dados" },
  { slug: "pecan-ai", name: "Pecan AI", tagline: "Previsões de negócio com IA generativa", description: "Plataforma de IA preditiva para equipes de dados gerarem previsões de negócio.", websiteUrl: "https://www.pecan.ai", pricingModel: "CONTACT_SALES", categorySlug: "dados" },

  // Design & Branding
  { slug: "figma-ai", name: "Figma AI", tagline: "Recursos de IA dentro do Figma", description: "Conjunto de recursos de IA integrados à ferramenta de design Figma.", websiteUrl: "https://www.figma.com", pricingModel: "FREEMIUM", categorySlug: "design" },
  { slug: "canva-ai", name: "Canva (Magic Studio)", tagline: "Suite de IA generativa do Canva", description: "Conjunto de ferramentas de IA generativa integradas ao editor Canva.", websiteUrl: "https://www.canva.com/magic-studio", pricingModel: "FREEMIUM", categorySlug: "design" },
  { slug: "framer-ai", name: "Framer AI", tagline: "Geração de sites com IA", description: "Geração de sites completos e responsivos a partir de prompts de texto.", websiteUrl: "https://www.framer.com/ai", pricingModel: "FREEMIUM", categorySlug: "design" },
  { slug: "looka", name: "Looka", tagline: "Criação de logotipos com IA", description: "Gera logotipos e identidade visual de marca automaticamente.", websiteUrl: "https://looka.com", pricingModel: "PAID", categorySlug: "design" },
  { slug: "brandmark", name: "Brandmark", tagline: "Gerador de identidade de marca com IA", description: "Cria logotipos e guias de marca completos a partir de palavras-chave.", websiteUrl: "https://brandmark.io", pricingModel: "PAID", categorySlug: "design" },
  { slug: "designs-ai", name: "Designs.ai", tagline: "Suite de design gráfico com IA", description: "Conjunto de ferramentas de IA para criar logos, vídeos e copy de design.", websiteUrl: "https://designs.ai", pricingModel: "FREEMIUM", categorySlug: "design" },
  { slug: "uizard", name: "Uizard", tagline: "Protótipos de UI gerados por IA", description: "Transforma esboços e prompts de texto em protótipos de interface navegáveis.", websiteUrl: "https://uizard.io", pricingModel: "FREEMIUM", categorySlug: "design" },
  { slug: "galileo-ai", name: "Galileo AI", tagline: "Geração de UI a partir de texto", description: "Gera designs de interface editáveis a partir de descrições em texto.", websiteUrl: "https://www.usegalileo.ai", pricingModel: "PAID", categorySlug: "design" },
  { slug: "khroma", name: "Khroma", tagline: "Paletas de cores personalizadas com IA", description: "IA que aprende suas preferências de cor e gera paletas personalizadas.", websiteUrl: "https://www.khroma.co", pricingModel: "FREE", categorySlug: "design" },
  { slug: "visily", name: "Visily", tagline: "Wireframes e protótipos com IA", description: "Cria wireframes e protótipos de UI a partir de screenshots ou esboços.", websiteUrl: "https://www.visily.ai", pricingModel: "FREEMIUM", categorySlug: "design" },

  // Marketing & Vendas
  { slug: "smartwriter-ai", name: "Smartwriter.ai", tagline: "Prospecção fria personalizada com IA", description: "Gera e-mails de prospecção personalizados em escala usando dados públicos.", websiteUrl: "https://smartwriter.ai", pricingModel: "PAID", categorySlug: "marketing" },
  { slug: "lavender", name: "Lavender", tagline: "Coach de e-mail de vendas com IA", description: "Analisa e melhora e-mails de vendas em tempo real antes do envio.", websiteUrl: "https://www.lavender.ai", pricingModel: "FREEMIUM", categorySlug: "marketing" },
  { slug: "apollo-io", name: "Apollo.io", tagline: "Plataforma de prospecção e dados de vendas", description: "Base de contatos B2B com automação de prospecção e recursos de IA.", websiteUrl: "https://www.apollo.io", pricingModel: "FREEMIUM", categorySlug: "marketing" },
  { slug: "clay", name: "Clay", tagline: "Enriquecimento de dados e prospecção com IA", description: "Combina dados de múltiplas fontes para personalizar prospecção em escala.", websiteUrl: "https://www.clay.com", pricingModel: "FREEMIUM", categorySlug: "marketing" },
  { slug: "gong", name: "Gong", tagline: "Inteligência de receita com IA", description: "Analisa chamadas e e-mails de vendas para gerar insights de receita.", websiteUrl: "https://www.gong.io", pricingModel: "CONTACT_SALES", categorySlug: "marketing" },
  { slug: "crystal-knows", name: "Crystal Knows", tagline: "Perfis de personalidade para vendas com IA", description: "Prevê traços de personalidade de leads para personalizar abordagens de venda.", websiteUrl: "https://www.crystalknows.com", pricingModel: "PAID", categorySlug: "marketing" },
  { slug: "persado", name: "Persado", tagline: "Linguagem de marketing otimizada por IA", description: "Gera e otimiza linguagem de campanhas de marketing usando IA generativa.", websiteUrl: "https://www.persado.com", pricingModel: "CONTACT_SALES", categorySlug: "marketing" },
  { slug: "regie-ai", name: "Regie.ai", tagline: "Conteúdo de prospecção gerado por IA", description: "Gera e otimiza sequências de prospecção de vendas com IA generativa.", websiteUrl: "https://www.regie.ai", pricingModel: "CONTACT_SALES", categorySlug: "marketing" },
  { slug: "postwise", name: "Postwise", tagline: "Crescimento no X (Twitter) com IA", description: "Geração e agendamento de posts para crescer audiência no X com IA.", websiteUrl: "https://postwise.ai", pricingModel: "PAID", categorySlug: "marketing" },
  { slug: "ocoya", name: "Ocoya", tagline: "Gestão de redes sociais com IA", description: "Geração de conteúdo, agendamento e analytics de redes sociais em um só lugar.", websiteUrl: "https://www.ocoya.com", pricingModel: "FREEMIUM", categorySlug: "marketing" },
  { slug: "seventh-sense", name: "Seventh Sense", tagline: "Otimização de horário de envio de e-mail com IA", description: "Usa IA para enviar e-mails de marketing no melhor horário para cada contato.", websiteUrl: "https://www.theseventhsense.com", pricingModel: "PAID", categorySlug: "marketing" },

  // Atendimento ao Cliente
  { slug: "intercom-fin", name: "Intercom Fin", tagline: "Agente de suporte de IA do Intercom", description: "Agente de atendimento ao cliente com IA integrado à plataforma Intercom.", websiteUrl: "https://www.intercom.com/fin", pricingModel: "CONTACT_SALES", categorySlug: "atendimento" },
  { slug: "zendesk-ai", name: "Zendesk AI", tagline: "IA de atendimento integrada ao Zendesk", description: "Recursos de IA para automação de respostas e triagem de tickets de suporte.", websiteUrl: "https://www.zendesk.com/service/ai", pricingModel: "CONTACT_SALES", categorySlug: "atendimento" },
  { slug: "drift", name: "Drift", tagline: "Chat de vendas e marketing com IA", description: "Plataforma de chat conversacional para qualificação de leads em tempo real.", websiteUrl: "https://www.drift.com", pricingModel: "CONTACT_SALES", categorySlug: "atendimento" },
  { slug: "ada-cx", name: "Ada", tagline: "Automação de atendimento ao cliente com IA", description: "Plataforma de automação de atendimento ao cliente com agentes de IA.", websiteUrl: "https://www.ada.cx", pricingModel: "CONTACT_SALES", categorySlug: "atendimento" },
  { slug: "tidio", name: "Tidio", tagline: "Chat e helpdesk com IA para PMEs", description: "Chat ao vivo e chatbot de IA para atendimento de pequenas e médias empresas.", websiteUrl: "https://www.tidio.com", pricingModel: "FREEMIUM", categorySlug: "atendimento" },
  { slug: "chatbase", name: "Chatbase", tagline: "Crie chatbots de IA com seus próprios dados", description: "Cria chatbots de atendimento treinados com os documentos da sua empresa.", websiteUrl: "https://www.chatbase.co", pricingModel: "FREEMIUM", categorySlug: "atendimento" },
  { slug: "voiceflow", name: "Voiceflow", tagline: "Construa agentes de IA conversacionais", description: "Plataforma visual para projetar e implantar agentes conversacionais de IA.", websiteUrl: "https://www.voiceflow.com", pricingModel: "FREEMIUM", categorySlug: "atendimento" },
  { slug: "botpress", name: "Botpress", tagline: "Plataforma open-source de chatbots com IA", description: "Plataforma de desenvolvimento de chatbots e agentes de IA conversacional.", websiteUrl: "https://botpress.com", pricingModel: "FREEMIUM", categorySlug: "atendimento" },
  { slug: "manychat", name: "ManyChat", tagline: "Automação de chat para Instagram e WhatsApp", description: "Automação de conversas de marketing e vendas via redes sociais e WhatsApp.", websiteUrl: "https://manychat.com", pricingModel: "FREEMIUM", categorySlug: "atendimento" },
  { slug: "forethought", name: "Forethought", tagline: "IA generativa para suporte ao cliente", description: "Automatiza resolução de tickets de suporte usando IA generativa.", websiteUrl: "https://www.forethought.ai", pricingModel: "CONTACT_SALES", categorySlug: "atendimento" },
  { slug: "yellow-ai", name: "Yellow.ai", tagline: "Plataforma de agentes de IA para atendimento", description: "Automação de atendimento ao cliente multicanal com agentes de IA.", websiteUrl: "https://yellow.ai", pricingModel: "CONTACT_SALES", categorySlug: "atendimento" },
  { slug: "freshdesk-freddy", name: "Freshdesk (Freddy AI)", tagline: "IA de suporte integrada ao Freshdesk", description: "Assistente de IA integrado ao helpdesk Freshdesk para triagem e respostas.", websiteUrl: "https://www.freshworks.com/freshdesk", pricingModel: "FREEMIUM", categorySlug: "atendimento" },

  // Automação & Workflows
  { slug: "uipath", name: "UiPath", tagline: "Plataforma líder de automação robótica", description: "Plataforma de RPA empresarial para automatizar processos repetitivos.", websiteUrl: "https://www.uipath.com", pricingModel: "CONTACT_SALES", categorySlug: "automacao" },
  { slug: "automation-anywhere", name: "Automation Anywhere", tagline: "RPA com IA para automação corporativa", description: "Plataforma de automação de processos robóticos com recursos de IA.", websiteUrl: "https://www.automationanywhere.com", pricingModel: "CONTACT_SALES", categorySlug: "automacao" },
  { slug: "power-automate", name: "Microsoft Power Automate", tagline: "Automação de processos da Microsoft", description: "Ferramenta de automação de fluxos de trabalho integrada ao ecossistema Microsoft.", websiteUrl: "https://www.microsoft.com/power-platform/products/power-automate", pricingModel: "FREEMIUM", categorySlug: "automacao" },
  { slug: "ifttt", name: "IFTTT", tagline: "Automação simples entre apps e dispositivos", description: "Conecta aplicativos e dispositivos com automações simples baseadas em gatilhos.", websiteUrl: "https://ifttt.com", pricingModel: "FREEMIUM", categorySlug: "automacao" },
  { slug: "pipedream", name: "Pipedream", tagline: "Automação de workflows para desenvolvedores", description: "Plataforma de automação e integração de APIs com foco em desenvolvedores.", websiteUrl: "https://pipedream.com", pricingModel: "FREEMIUM", categorySlug: "automacao" },
  { slug: "workato", name: "Workato", tagline: "Automação corporativa entre sistemas", description: "Plataforma de automação e integração de sistemas para empresas.", websiteUrl: "https://www.workato.com", pricingModel: "CONTACT_SALES", categorySlug: "automacao" },
  { slug: "relay-app", name: "Relay.app", tagline: "Automação de workflows com IA e humanos no loop", description: "Automação de fluxos de trabalho combinando IA com etapas de aprovação humana.", websiteUrl: "https://www.relay.app", pricingModel: "FREEMIUM", categorySlug: "automacao" },
  { slug: "bardeen", name: "Bardeen", tagline: "Automação de tarefas repetitivas no navegador", description: "Automatiza tarefas repetitivas direto no navegador com IA.", websiteUrl: "https://www.bardeen.ai", pricingModel: "FREEMIUM", categorySlug: "automacao" },
  { slug: "levity", name: "Levity", tagline: "Automação no-code com IA para PMEs", description: "Automação de tarefas baseadas em texto, imagem e e-mail sem código.", websiteUrl: "https://levity.ai", pricingModel: "PAID", categorySlug: "automacao" },

  // SEO & Otimização de Conteúdo
  { slug: "surfer-seo", name: "Surfer SEO", tagline: "Otimização de conteúdo para SEO com dados", description: "Analisa páginas concorrentes para guiar a otimização de conteúdo para SEO.", websiteUrl: "https://surferseo.com", pricingModel: "PAID", categorySlug: "seo" },
  { slug: "neuronwriter", name: "NeuronWriter", tagline: "Otimização de conteúdo baseada em NLP", description: "Otimização de conteúdo para SEO usando análise semântica de concorrentes.", websiteUrl: "https://neuronwriter.com", pricingModel: "PAID", categorySlug: "seo" },
  { slug: "frase-io", name: "Frase", tagline: "Pesquisa e otimização de conteúdo com IA", description: "Pesquisa de palavras-chave e otimização de briefing de conteúdo com IA.", websiteUrl: "https://www.frase.io", pricingModel: "PAID", categorySlug: "seo" },
  { slug: "marketmuse", name: "MarketMuse", tagline: "Estratégia de conteúdo orientada por IA", description: "Planejamento e auditoria de estratégia de conteúdo usando IA.", websiteUrl: "https://www.marketmuse.com", pricingModel: "PAID", categorySlug: "seo" },
  { slug: "clearscope", name: "Clearscope", tagline: "Otimização de conteúdo para buscadores", description: "Análise de relevância semântica para otimizar conteúdo para SEO.", websiteUrl: "https://www.clearscope.io", pricingModel: "PAID", categorySlug: "seo" },
  { slug: "originality-ai", name: "Originality.ai", tagline: "Detecção de plágio e conteúdo de IA para SEO", description: "Verifica plágio e conteúdo gerado por IA antes da publicação.", websiteUrl: "https://originality.ai", pricingModel: "PAID", categorySlug: "seo" },
  { slug: "scalenut", name: "Scalenut", tagline: "Plataforma de SEO e conteúdo com IA", description: "Planejamento, redação e otimização de conteúdo de SEO em uma plataforma.", websiteUrl: "https://www.scalenut.com", pricingModel: "PAID", categorySlug: "seo" },
  { slug: "outranking", name: "Outranking", tagline: "Workflow de SEO com IA generativa", description: "Combina pesquisa de SEO e geração de conteúdo em um workflow guiado.", websiteUrl: "https://www.outranking.io", pricingModel: "PAID", categorySlug: "seo" },

  // Educação & Aprendizado
  { slug: "khanmigo", name: "Khanmigo", tagline: "Tutor de IA da Khan Academy", description: "Tutor de IA da Khan Academy que guia estudantes sem dar respostas prontas.", websiteUrl: "https://www.khanacademy.org/khan-labs", pricingModel: "FREEMIUM", categorySlug: "educacao" },
  { slug: "duolingo-max", name: "Duolingo Max", tagline: "Aprendizado de idiomas com IA generativa", description: "Recursos de IA generativa do Duolingo para prática de conversação e explicações.", websiteUrl: "https://www.duolingo.com", pricingModel: "PAID", categorySlug: "educacao" },
  { slug: "elsa-speak", name: "ELSA Speak", tagline: "Treino de pronúncia em inglês com IA", description: "Aplicativo de IA para treinar pronúncia e fluência em inglês.", websiteUrl: "https://elsaspeak.com", pricingModel: "FREEMIUM", categorySlug: "educacao" },
  { slug: "speak", name: "Speak", tagline: "Prática de conversação em idiomas com IA", description: "Aprendizado de idiomas com prática de conversação guiada por IA.", websiteUrl: "https://www.usespeak.com", pricingModel: "PAID", categorySlug: "educacao" },
  { slug: "quizlet", name: "Quizlet", tagline: "Estudo com flashcards e IA (Q-Chat)", description: "Plataforma de estudo com flashcards e tutor de IA conversacional.", websiteUrl: "https://quizlet.com", pricingModel: "FREEMIUM", categorySlug: "educacao" },
  { slug: "coursera-coach", name: "Coursera Coach", tagline: "Tutor de IA para cursos online", description: "Assistente de IA da Coursera que tira dúvidas durante os cursos.", websiteUrl: "https://www.coursera.org", pricingModel: "FREEMIUM", categorySlug: "educacao" },
  { slug: "socratic", name: "Socratic", tagline: "Ajuda com lição de casa via IA do Google", description: "Aplicativo do Google que ajuda estudantes a entender problemas escolares.", websiteUrl: "https://socratic.org", pricingModel: "FREE", categorySlug: "educacao" },
  { slug: "photomath", name: "Photomath", tagline: "Resolução de problemas de matemática com IA", description: "Resolve problemas matemáticos fotografados, explicando o passo a passo.", websiteUrl: "https://photomath.com", pricingModel: "FREEMIUM", categorySlug: "educacao" },

  // Saúde
  { slug: "ada-health", name: "Ada Health", tagline: "Avaliação de sintomas com IA", description: "Aplicativo de avaliação de sintomas e orientação de saúde baseado em IA.", websiteUrl: "https://ada.com", pricingModel: "FREEMIUM", categorySlug: "saude" },
  { slug: "nuance-dax", name: "Nuance DAX", tagline: "Documentação clínica ambiental com IA", description: "Assistente de IA da Microsoft/Nuance que documenta consultas médicas automaticamente.", websiteUrl: "https://www.nuance.com/healthcare/dragon-ambient-experience.html", pricingModel: "CONTACT_SALES", categorySlug: "saude" },
  { slug: "abridge", name: "Abridge", tagline: "Resumo de consultas médicas com IA", description: "Gera resumos clínicos automáticos a partir de conversas entre médico e paciente.", websiteUrl: "https://www.abridge.com", pricingModel: "CONTACT_SALES", categorySlug: "saude" },
  { slug: "suki-ai", name: "Suki AI", tagline: "Assistente de voz clínico com IA", description: "Assistente de voz com IA que reduz o trabalho administrativo de médicos.", websiteUrl: "https://www.suki.ai", pricingModel: "CONTACT_SALES", categorySlug: "saude" },
  { slug: "hippocratic-ai", name: "Hippocratic AI", tagline: "Agentes de IA para tarefas de saúde", description: "Modelos de IA voltados a tarefas de atendimento ao paciente de baixo risco.", websiteUrl: "https://www.hippocraticai.com", pricingModel: "CONTACT_SALES", categorySlug: "saude" },
  { slug: "woebot", name: "Woebot", tagline: "Chatbot de saúde mental com IA", description: "Chatbot de apoio emocional baseado em terapia cognitivo-comportamental.", websiteUrl: "https://woebothealth.com", pricingModel: "FREEMIUM", categorySlug: "saude" },
  { slug: "wysa", name: "Wysa", tagline: "Assistente de bem-estar emocional com IA", description: "Aplicativo de apoio à saúde mental com chatbot empático de IA.", websiteUrl: "https://www.wysa.io", pricingModel: "FREEMIUM", categorySlug: "saude" },

  // Jurídico
  { slug: "harvey", name: "Harvey", tagline: "IA jurídica para grandes escritórios", description: "Plataforma de IA generativa especializada em fluxos de trabalho jurídicos.", websiteUrl: "https://www.harvey.ai", pricingModel: "CONTACT_SALES", categorySlug: "juridico" },
  { slug: "casetext", name: "CoCounsel (Casetext)", tagline: "Assistente jurídico de IA", description: "Assistente de IA para pesquisa jurídica, revisão de documentos e due diligence.", websiteUrl: "https://casetext.com", pricingModel: "CONTACT_SALES", categorySlug: "juridico" },
  { slug: "spellbook", name: "Spellbook", tagline: "Revisão de contratos com IA", description: "Assistente de IA que revisa e sugere cláusulas em contratos direto no Word.", websiteUrl: "https://www.spellbook.legal", pricingModel: "PAID", categorySlug: "juridico" },
  { slug: "donotpay", name: "DoNotPay", tagline: "Advogado robô para consumidores", description: "Ferramenta automatizada para disputar cobranças e resolver questões legais simples.", websiteUrl: "https://donotpay.com", pricingModel: "PAID", categorySlug: "juridico" },
  { slug: "ironclad-ai", name: "Ironclad AI", tagline: "Gestão de contratos com IA", description: "Plataforma de gestão do ciclo de vida de contratos com análise de IA.", websiteUrl: "https://ironcladapp.com", pricingModel: "CONTACT_SALES", categorySlug: "juridico" },
  { slug: "luminance", name: "Luminance", tagline: "Análise de contratos com IA", description: "Plataforma de IA para análise e negociação de contratos em escala.", websiteUrl: "https://www.luminance.com", pricingModel: "CONTACT_SALES", categorySlug: "juridico" },
  { slug: "lawgeex", name: "LawGeex", tagline: "Revisão automática de contratos", description: "Automatiza a revisão e aprovação de contratos rotineiros com IA.", websiteUrl: "https://www.lawgeex.com", pricingModel: "CONTACT_SALES", categorySlug: "juridico" },

  // Finanças
  { slug: "cleo", name: "Cleo", tagline: "Assistente financeiro pessoal com IA", description: "Chatbot de finanças pessoais que ajuda a economizar e entender gastos.", websiteUrl: "https://www.meetcleo.com", pricingModel: "FREEMIUM", categorySlug: "financas" },
  { slug: "vic-ai", name: "Vic.ai", tagline: "Automação de contas a pagar com IA", description: "Automatiza processamento de faturas e contas a pagar usando IA.", websiteUrl: "https://www.vic.ai", pricingModel: "CONTACT_SALES", categorySlug: "financas" },
  { slug: "booke-ai", name: "Booke AI", tagline: "Automação de contabilidade com IA", description: "Automatiza categorização de transações e reconciliação contábil.", websiteUrl: "https://www.booke.ai", pricingModel: "PAID", categorySlug: "financas" },
  { slug: "rogo", name: "Rogo", tagline: "IA para análise financeira em bancos", description: "Assistente de IA para análise financeira usado por bancos de investimento.", websiteUrl: "https://rogo.ai", pricingModel: "CONTACT_SALES", categorySlug: "financas" },
  { slug: "rocket-money", name: "Rocket Money", tagline: "Gestão de assinaturas e finanças com IA", description: "Identifica e cancela assinaturas indesejadas, ajudando no orçamento pessoal.", websiteUrl: "https://www.rocketmoney.com", pricingModel: "FREEMIUM", categorySlug: "financas" },
  { slug: "origin", name: "Origin", tagline: "Plataforma de bem-estar financeiro com IA", description: "Planejamento financeiro pessoal com IA, usado como benefício corporativo.", websiteUrl: "https://www.useorigin.com", pricingModel: "CONTACT_SALES", categorySlug: "financas" },

  // Reuniões & Transcrição
  { slug: "otter-ai", name: "Otter.ai", tagline: "Transcrição e resumo de reuniões com IA", description: "Transcreve reuniões em tempo real e gera resumos e itens de ação automaticamente.", websiteUrl: "https://otter.ai", pricingModel: "FREEMIUM", categorySlug: "reunioes" },
  { slug: "fireflies-ai", name: "Fireflies.ai", tagline: "Gravação e transcrição de reuniões com IA", description: "Grava, transcreve e busca trechos de reuniões automaticamente.", websiteUrl: "https://fireflies.ai", pricingModel: "FREEMIUM", categorySlug: "reunioes" },
  { slug: "fathom-video", name: "Fathom", tagline: "Assistente de notas de reunião gratuito", description: "Grava e resume reuniões de vídeo automaticamente, com itens de ação.", websiteUrl: "https://fathom.video", pricingModel: "FREEMIUM", categorySlug: "reunioes" },
  { slug: "tldv", name: "tl;dv", tagline: "Gravação e resumo de chamadas com IA", description: "Grava chamadas de vídeo e gera resumos e clipes automaticamente.", websiteUrl: "https://tldv.io", pricingModel: "FREEMIUM", categorySlug: "reunioes" },
  { slug: "avoma", name: "Avoma", tagline: "Inteligência de reuniões e conversas com IA", description: "Transcrição, resumo e análise de reuniões para equipes de vendas e CS.", websiteUrl: "https://www.avoma.com", pricingModel: "PAID", categorySlug: "reunioes" },
  { slug: "sembly-ai", name: "Sembly AI", tagline: "Assistente de reuniões corporativas com IA", description: "Transcrição e geração de minutas inteligentes para reuniões de trabalho.", websiteUrl: "https://www.sembly.ai", pricingModel: "FREEMIUM", categorySlug: "reunioes" },
  { slug: "supernormal", name: "Supernormal", tagline: "Notas de reunião automáticas com IA", description: "Gera notas de reunião automaticamente a partir de chamadas de vídeo.", websiteUrl: "https://supernormal.com", pricingModel: "FREEMIUM", categorySlug: "reunioes" },
  { slug: "read-ai", name: "Read AI", tagline: "Resumos e métricas de reuniões com IA", description: "Resume reuniões, e-mails e mensagens, com métricas de participação.", websiteUrl: "https://www.read.ai", pricingModel: "FREEMIUM", categorySlug: "reunioes" },

  // Notas & Conhecimento
  { slug: "tana", name: "Tana", tagline: "Workspace de conhecimento com IA", description: "Ferramenta de notas estruturadas com IA para organizar conhecimento pessoal.", websiteUrl: "https://tana.inc", pricingModel: "FREEMIUM", categorySlug: "notas" },
  { slug: "heptabase", name: "Heptabase", tagline: "Mapa visual de conhecimento com IA", description: "Organiza notas e ideias em mapas visuais conectados.", websiteUrl: "https://heptabase.com", pricingModel: "FREEMIUM", categorySlug: "notas" },
  { slug: "remnote", name: "RemNote", tagline: "Notas com repetição espaçada e IA", description: "Combina notas, flashcards de repetição espaçada e recursos de IA para estudo.", websiteUrl: "https://www.remnote.com", pricingModel: "FREEMIUM", categorySlug: "notas" },
  { slug: "glean", name: "Glean", tagline: "Busca corporativa de conhecimento com IA", description: "Motor de busca empresarial que conecta e indexa o conhecimento da empresa.", websiteUrl: "https://www.glean.com", pricingModel: "CONTACT_SALES", categorySlug: "notas" },
  { slug: "mymind", name: "Mymind", tagline: "Segundo cérebro automático com IA", description: "Salva e organiza automaticamente links, notas e ideias sem esforço manual.", websiteUrl: "https://mymind.com", pricingModel: "PAID", categorySlug: "notas" },

  // Apresentações & Slides
  { slug: "gamma-app", name: "Gamma", tagline: "Apresentações geradas por IA", description: "Gera apresentações, documentos e páginas web a partir de um prompt de texto.", websiteUrl: "https://gamma.app", pricingModel: "FREEMIUM", categorySlug: "apresentacoes" },
  { slug: "beautiful-ai", name: "Beautiful.ai", tagline: "Slides com design automático com IA", description: "Cria apresentações com design automático que se ajusta enquanto você edita.", websiteUrl: "https://www.beautiful.ai", pricingModel: "FREEMIUM", categorySlug: "apresentacoes" },
  { slug: "tome-app", name: "Tome", tagline: "Narrativas visuais geradas por IA", description: "Gera apresentações e narrativas visuais a partir de prompts de texto.", websiteUrl: "https://tome.app", pricingModel: "FREEMIUM", categorySlug: "apresentacoes" },
  { slug: "pitch", name: "Pitch", tagline: "Apresentações colaborativas com IA", description: "Ferramenta de apresentações colaborativa com templates e recursos de IA.", websiteUrl: "https://pitch.com", pricingModel: "FREEMIUM", categorySlug: "apresentacoes" },
  { slug: "plus-ai", name: "Plus AI", tagline: "Geração de slides dentro do Google Slides", description: "Gera e edita apresentações de IA direto no Google Slides e PowerPoint.", websiteUrl: "https://www.plusai.com", pricingModel: "FREEMIUM", categorySlug: "apresentacoes" },
  { slug: "decktopus", name: "Decktopus", tagline: "Criação automática de apresentações", description: "Gera apresentações completas automaticamente a partir de um briefing simples.", websiteUrl: "https://www.decktopus.com", pricingModel: "FREEMIUM", categorySlug: "apresentacoes" },
  { slug: "slidebean", name: "Slidebean", tagline: "Design automático de pitch decks", description: "Cria pitch decks com design automático para startups.", websiteUrl: "https://slidebean.com", pricingModel: "FREEMIUM", categorySlug: "apresentacoes" },

  // Criação de Sites
  { slug: "durable", name: "Durable", tagline: "Criação de sites em segundos com IA", description: "Gera um site completo com texto e imagens em menos de um minuto.", websiteUrl: "https://durable.co", pricingModel: "FREEMIUM", categorySlug: "sites" },
  { slug: "10web", name: "10Web", tagline: "Construção de sites WordPress com IA", description: "Gera e hospeda sites WordPress automaticamente usando IA.", websiteUrl: "https://10web.io", pricingModel: "FREEMIUM", categorySlug: "sites" },
  { slug: "wix-ai", name: "Wix AI", tagline: "Criação de sites guiada por IA", description: "Construtor de sites Wix com geração de design e conteúdo via IA.", websiteUrl: "https://www.wix.com", pricingModel: "FREEMIUM", categorySlug: "sites" },
  { slug: "hostinger-ai", name: "Hostinger AI Website Builder", tagline: "Construtor de sites com IA da Hostinger", description: "Gera sites completos automaticamente como parte da hospedagem Hostinger.", websiteUrl: "https://www.hostinger.com/website-builder", pricingModel: "PAID", categorySlug: "sites" },
  { slug: "dora-ai", name: "Dora AI", tagline: "Sites 3D e animados gerados por IA", description: "Gera sites com animações e elementos 3D a partir de prompts de texto.", websiteUrl: "https://www.dora.run", pricingModel: "FREEMIUM", categorySlug: "sites" },
  { slug: "webflow-ai", name: "Webflow AI", tagline: "Recursos de IA no construtor Webflow", description: "Recursos de geração de conteúdo e design integrados ao Webflow.", websiteUrl: "https://webflow.com", pricingModel: "FREEMIUM", categorySlug: "sites" },
  { slug: "unbounce-smart-copy", name: "Unbounce Smart Copy", tagline: "Copy de landing pages com IA", description: "Geração de copy para landing pages e anúncios integrada ao Unbounce.", websiteUrl: "https://unbounce.com/product/smart-copy", pricingModel: "PAID", categorySlug: "sites" },

  // Detecção de Conteúdo de IA
  { slug: "gptzero", name: "GPTZero", tagline: "Detecção de texto gerado por IA", description: "Ferramenta para detectar se um texto foi escrito por IA ou por humanos.", websiteUrl: "https://gptzero.me", pricingModel: "FREEMIUM", categorySlug: "deteccao" },
  { slug: "copyleaks", name: "Copyleaks", tagline: "Detecção de plágio e conteúdo de IA", description: "Plataforma de detecção de plágio e de texto gerado por IA para educação e empresas.", websiteUrl: "https://copyleaks.com", pricingModel: "FREEMIUM", categorySlug: "deteccao" },
  { slug: "winston-ai", name: "Winston AI", tagline: "Detector de conteúdo de IA e plágio", description: "Detecta conteúdo gerado por IA e plágio com alta precisão.", websiteUrl: "https://gowinston.ai", pricingModel: "FREEMIUM", categorySlug: "deteccao" },
  { slug: "sapling-ai", name: "Sapling", tagline: "Detecção de IA e assistente de escrita para suporte", description: "Detector de conteúdo de IA e assistente de escrita para equipes de atendimento.", websiteUrl: "https://sapling.ai", pricingModel: "FREEMIUM", categorySlug: "deteccao" },
  { slug: "turnitin", name: "Turnitin", tagline: "Detecção de plágio acadêmico e IA", description: "Plataforma acadêmica de detecção de plágio e de texto gerado por IA.", websiteUrl: "https://www.turnitin.com", pricingModel: "CONTACT_SALES", categorySlug: "deteccao" },
  { slug: "content-at-scale-detector", name: "Content at Scale AI Detector", tagline: "Detector gratuito de conteúdo de IA", description: "Ferramenta gratuita para identificar conteúdo gerado por modelos de IA.", websiteUrl: "https://contentatscale.ai/ai-content-detector", pricingModel: "FREE", categorySlug: "deteccao" },

  // 3D & Jogos
  { slug: "promethean-ai", name: "Promethean AI", tagline: "Criação de mundos 3D com IA", description: "Assistente de IA para artistas criarem cenários 3D para jogos e mídia.", websiteUrl: "https://www.prometheanai.com", pricingModel: "FREEMIUM", categorySlug: "3d-jogos" },
  { slug: "inworld-ai", name: "Inworld AI", tagline: "NPCs com IA para jogos", description: "Plataforma para criar personagens de jogos com personalidade e diálogo via IA.", websiteUrl: "https://inworld.ai", pricingModel: "FREEMIUM", categorySlug: "3d-jogos" },
  { slug: "kaedim", name: "Kaedim", tagline: "Geração de modelos 3D a partir de imagens", description: "Converte imagens 2D em modelos 3D prontos para uso em jogos e produtos.", websiteUrl: "https://www.kaedim3d.com", pricingModel: "PAID", categorySlug: "3d-jogos" },
  { slug: "meshy-ai", name: "Meshy", tagline: "Geração de modelos 3D a partir de texto", description: "Gera modelos 3D texturizados a partir de descrições de texto ou imagens.", websiteUrl: "https://www.meshy.ai", pricingModel: "FREEMIUM", categorySlug: "3d-jogos" },
  { slug: "spline-ai", name: "Spline AI", tagline: "Design 3D colaborativo com IA", description: "Ferramenta de design 3D para web com recursos de geração via IA.", websiteUrl: "https://spline.design", pricingModel: "FREEMIUM", categorySlug: "3d-jogos" },
  { slug: "rosebud-ai", name: "Rosebud AI", tagline: "Criação de jogos com IA generativa", description: "Plataforma para criar jogos e personagens usando IA generativa.", websiteUrl: "https://rosebud.ai", pricingModel: "FREEMIUM", categorySlug: "3d-jogos" },
  { slug: "anything-world", name: "Anything World", tagline: "Animação automática de modelos 3D com IA", description: "Anima automaticamente qualquer modelo 3D usando IA, sem rigging manual.", websiteUrl: "https://anything.world", pricingModel: "CONTACT_SALES", categorySlug: "3d-jogos" },
];
